### PR TITLE
got rid of ".php" file specifier in urls

### PR DESCRIPTION
**Pull request by stephanlindauer**

### CODE REVIEW

**Comment by zutrinken** [comment]
@stephanlindauer did this work for you without any mod rewrite? I've added a .htaccess file to the project that (at least) make it work locally (for me). Do you know if the server supports mod rewrite?

**Comment by stephanlindauer** [comment]
the server does support it but its supported from the global settings and not the .htaccess in the current dir. can you maybe commit your htaccess so we are sure to not break our local dev environments?

btw: the reason why i setup everything so it only works from the root is because i set up a local subdomain for every project. this way i can access my projects via http://criticalmaps.localhost.com for example. that way i can rely on absolute paths in resource specifications even on localhost.
(http://www.axertion.com/tutorials/2012/03/how-to-setup-local-subdomains-using-wampserver/ )

**Comment by zutrinken** [comment]
@stephanlindauer works without .htaccess on the server. So the .htaccess is only useful for local development. hooray.

**Comment by stephanlindauer** [comment]
can you push your .htaccess anyway, to make it easier for future contributors to get this thing running on their system?

**Pull request merged**
