### PR TITLE
add julian

### PR DESCRIPTION
**Pull request by stephanlindauer**
ptal

### CODE REVIEW

**Comment by stephanlindauer** [comment]
i thought i would just introduce some chronological order. maybe it would make sense to have sections where we just put the names. wdyt?

**Comment by zutrinken** [comment]
Chronological is good, but I think it's too late unless you know the history order. How about making it alphabetically? Seems straight forward and understandable to me. Sorry for blowing this minor change up 🙃

**Comment by stephanlindauer** [comment]
no i think you are right. my OCD is always kicking in when i see that list. :D
will change later today to alphabetical order. :)

**Comment by stephanlindauer** [comment]
done @zutrinken

**Review by zutrinken — APPROVED** [review]
👌

**Pull request merged**
