### PR TITLE
update assets and project structure

### PR DESCRIPTION
**Pull request by zutrinken**
Sorry for that one monster commit, but it was some kind of try and error building without any specific goal, which lead to this.

I tried to keep the current style (for the moment) and aligned all assets, styles and project structure. Feel free to make some remarks and requirements before merging.

### CODE REVIEW

**Comment by stephanlindauer** [comment]
mega nice!

**Comment by stephanlindauer** [comment]
is live

**Comment by headione** [comment]
this looks AMAZING!

**Comment by stephanlindauer** [comment]
:+1:

**Pull request merged**
