### PR TITLE
use bower for components, build CSS with SASS and JS with uglify

### PR DESCRIPTION
**Pull request by zutrinken**
I've integrated leaflet, leaflet-hash, jQuery, normalize and modernizer via bower components. Than added two grunt task. One for development that also starts a watch task `$ grunt dev` and one to prepare the upload folder `$ grunt build`. Now the CSS will be built by SASS with auto prefixing and minifying as well as uglifying all JS files.

Please check if the `grunt default` still works fine with your CI.

### CODE REVIEW

**Comment by zutrinken** [comment]
@stephanlindauer I removed all compiled files and only kept the src folder. Also combined the distribution with the CI task. Does this work properly?

**Comment by zutrinken** [comment]
@stephanlindauer I think it has to be broken, since the grunt task depends on some bower files. Or does the CI also install bower components?

**Comment by stephanlindauer** [comment]
i think it should be fine after all those dependencies are in the package.json. i will merge. if stuff blows up then i will just do a roll back and we can look deeping into this.

**Comment by stephanlindauer** [comment]
hm. something went wrong. i will send you ftp credentials so you have full access to the webserver. one thing to keep in mind is that deployments via the ftp-upload task can really only upload and not delete anything on the server but thats unlikely to be the problem.

**Comment by stephanlindauer** [comment]
also feel free to blow up live to test stuff. unless we build some kind of dev environment theres probably no other way to test stuff in the production environment..

**Pull request merged**
